language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: PHPDBG=0
    - php: 7.0
      env: PHPDBG=1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    
before_script:
  - if [[ "$PHPDBG" == "1" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update --no-interaction
  - composer install --prefer-dist --no-interaction --dev



script:
  - if [[ "$PHPDBG" == "0" ]]; then vendor/bin/phpspec run -v --no-interaction; fi
  - if [[ "$PHPDBG" == "1" ]]; then phpdbg -qrr vendor/bin/phpspec run -v --no-interaction; fi
  - vendor/bin/phpcs
  - vendor/bin/test-reporter
  - vendor/bin/codacycoverage clover
